remote_theme: jekyll-theme-plain/jekyll-theme-plain

# lang: en
# color_scheme: false # disables color scheme sync
title: Your awesome title
# url: https://USERNAME.github.io
# basename: 
# canonical_url: false # disables canonical URLs
# license_url: 

permalink: /:title

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      stylesheets:
        - post.css
