remote_theme: jekyll-theme-plain/jekyll-theme-plain

title: Your awesome title
# lang: en
# url: https://YOURDOMAIN.com
# basename: 
# license_url: 

# Disables sync with system theme
# color_scheme: false

# Disables canonical URLs.
# canonical_url: false

# To use a style sheet, place it in _includes/XXX.css and uncomment the following lines:
# stylesheets:
#   - XXX.css

# Page permalink.
collections:
  pages:
    output: true
    permalink: /:title/

# Post permalink.
permalink: /:year/:month/:title

# Front matter defaults for posts.
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      stylesheets:
        # - XXX.css
        - post.css
      title: "" # sets the URL as the title
