#!/usr/bin/env ruby
#
# Set up me as:
# ln -s ../../post-commit .git/hooks/post-commit
#
require 'date'
require 'yaml'

# The directory where the post files are stored.
post_dir = '_posts'

# The format string for the command to get the first commit date of a post
# file. `%s` will be replaced by the filename.
date_command_format = %q{TZ=UTC0 git log --follow --date=iso-local --format='%%cd' '%s' | tail -n 1}

# The regex that matches a post file name. Exclude filenames with a date.
# The year is intentionally limited to four digits to minimize confusion with
# original date-like filenames (thus having the Y10K problem).
POST_FILENAME_REGEXP = %r{\A(?!\d{4}-\d{2}-\d{2}-).*\.md\z}m.freeze()

# The regex that matches a YAML front matter.
# cf. https://github.com/jekyll/jekyll/blob/b7056373afc65935a073bddadfe70606b622ffa6/lib/jekyll/document.rb#L13
YAML_FRONT_MATTER_REGEXP = %r{\A(---\s*\n.*?\n?)^((---|\.\.\.)\s*$\n?)}m.freeze()

Dir.chdir(post_dir)

Dir.foreach('.') { |filename|
  if filename !~ POST_FILENAME_REGEXP
    next
  end

  if not File.file?(filename)
    next
  end

  front_matter = {}
  content = File.read(filename)

  match = content.match(YAML_FRONT_MATTER_REGEXP)
  if match
    # `match[1]` corresponds to the YAML body.
    front_matter = YAML.load(match[1]) || {}

    # `match.post_match` corresponds to the rest of the contents (post body).
    content = match.post_match
  end

  if not front_matter.has_key?('date')
    front_matter['date'] = `#{date_command_format % filename}`.chomp()
  end

  date = Date.parse(front_matter['date'])

  new_content = YAML.dump(front_matter).rstrip() + "\n---\n\n" + content
  File.write(filename, new_content)

  new_filename = date.strftime() + '-' + filename
  File.rename(filename, new_filename)
}
